language: elixir

elixir:
  - 1.4.5

otp_release:
  - 19.2

matrix:
  include:
    - elixir 1.4.5
      otp_release 20.0
    - elixir: 1.5.0
      otp_release: 20.0

script:
  - mix credo
  - mix test
